### PR TITLE
Be/feature/signup route

### PR DESCRIPTION
**Pull request by xAmiBa**
- New functions  in users repository
    - add(), find_by_id(), find_by_email()

- New functions in token_config.py:
   - token_checker()

- signup route created 
-  Signup route tested with use of playwright. Returns positive server response.

Screenshot 2023-12-14 at 13 30 49

### CODE REVIEW

**Review by Ovie-Eharisi-Ayomah — COMMENTED** [review]
In the context of the MVP, the unit tests are satisfactory.

**Review by PiotrSurowiec90 — COMMENTED** [review]
I'm happy with Create User enpoint. RDY to merge when Changes from previous review are included.

**Review by PiotrSurowiec90 — APPROVED** [review]
I'm happy with Create User enpoint. RDY to merge when Changes from previous review are included.

**Review by PiotrSurowiec90 — APPROVED** [review]
GREAT JOB!

**Pull request merged**
